apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: h2nqupl8p-go 
  janus-idp.io/tekton: h2nqupl8p-go
  backstage.io/kubernetes-id: h2nqupl8p-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: h2nqupl8p-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml